[project]
name = "scrapping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "lxml>=6.0.2",
    "pandas>=3.0.0",
    "playwright>=1.58.0",
    "pytest-playwright>=0.7.2",
    "requests>=2.32.5",
]
